CREATE TABLE IF NOT EXISTS pods (
   id INTEGER PRIMARY KEY AUTOINCREMENT,
   uid TEXT UNIQUE NOT NULL,
   pod_uid TEXT UNIQUE NOT NULL,
   pod_name TEXT NOT NULL,
   local_dir TEXT NOT NULL,
   remote_dir TEXT NOT NULL,
   file TEXT DEFAULT '',
   target TEXT DEFAULT '',
   status TEXT DEFAULT '',
   hostname TEXT DEFAULT '',
   ip TEXT DEFAULT '',
   replicas INTEGER DEFAULT 1,
   created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
   updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
   dismiss INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS records (
   id INTEGER PRIMARY KEY AUTOINCREMENT,
   pod_id INTEGER NOT NULL,
   content TEXT DEFAULT '',
   hostname TEXT DEFAULT '',
   ip TEXT DEFAULT '',
   FOREIGN KEY (pod_id) REFERENCES pods(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS domains (
   id INTEGER PRIMARY KEY AUTOINCREMENT,
   pod_id INTEGER NOT NULL,
   container_name TEXT DEFAULT '',
   domain TEXT DEFAULT '',
   created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
   updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
   dismiss INTEGER DEFAULT 0,
   FOREIGN KEY (pod_id) REFERENCES pods(id) ON DELETE CASCADE
);
